services:
  sphinx:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.python  # Chemin vers ton Dockerfile
    volumes:
      - ./docs:/docs  # Monter le dossier docs dans le conteneur
    command: make html  # Commande qui génère la documentation
